name: VercelPagesDeploy
on: [push, pull_request]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: jenkey2011/vuepress-deploy@v1.8.1
      env:
        ACCESS_TOKEN: ${{ secrets.VERCEL_DEPLOY }}
        TARGET_REPO: KiritaniAyaka/mtf-hrt-docs
        TARGET_BRANCH: vercel
        BUILD_SCRIPT: yarn && yarn docs:build
        BUILD_DIR: docs/.vuepress/dist/
        COMMIT_MESSAGE:  Vercel Pages Deploy
